// Code generated by goyacc - DO NOT EDIT.

package easylang

import __yyfmt__ "fmt"

var _context = newContext()

type yySymType struct {
	yys          int
	value        float64
	str          string
	expr         expression
	descriptions []string
	arguments    []expression
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault  = 57373
	yyEofCode  = 57344
	AND        = 57361
	COLONEQUAL = 57351
	COMMA      = 57354
	DIVIDE     = 57371
	DOLLAR     = 57358
	DOT        = 57356
	EQ         = 57362
	EQUALS     = 57349
	GE         = 57365
	GT         = 57364
	ID         = 57346
	LE         = 57367
	LPAREN     = 57352
	LT         = 57366
	MINUS      = 57368
	NE         = 57363
	NOT        = 57359
	NUM        = 57347
	OR         = 57360
	PARAMEQUAL = 57350
	PLUS       = 57369
	POUND      = 57357
	RPAREN     = 57353
	SEMI       = 57355
	STRING     = 57348
	TIMES      = 57370
	UNARY      = 57372
	yyErrCode  = 57345

	yyMaxDepth = 200
	yyTabOfs   = -43
)

var (
	yyPrec = map[int]int{
		OR:     0,
		AND:    1,
		EQ:     2,
		NE:     2,
		GT:     3,
		GE:     3,
		LT:     3,
		LE:     3,
		MINUS:  4,
		PLUS:   4,
		TIMES:  5,
		DIVIDE: 5,
		UNARY:  6,
	}

	yyXLAT = map[int]int{
		57368: 0,  // MINUS (51x)
		57354: 1,  // COMMA (41x)
		57355: 2,  // SEMI (37x)
		57360: 3,  // OR (35x)
		57353: 4,  // RPAREN (33x)
		57346: 5,  // ID (32x)
		57352: 6,  // LPAREN (32x)
		57347: 7,  // NUM (32x)
		57361: 8,  // AND (29x)
		57359: 9,  // NOT (29x)
		57348: 10, // STRING (29x)
		57362: 11, // EQ (27x)
		57363: 12, // NE (27x)
		57365: 13, // GE (25x)
		57364: 14, // GT (25x)
		57367: 15, // LE (25x)
		57366: 16, // LT (25x)
		57369: 17, // PLUS (22x)
		57383: 18, // postfix_expression (21x)
		57384: 19, // primary_expression (21x)
		57389: 20, // unary_expression (21x)
		57371: 21, // DIVIDE (17x)
		57382: 22, // multiplicative_expression (17x)
		57370: 23, // TIMES (17x)
		57374: 24, // additive_expression (15x)
		57385: 25, // relational_expression (11x)
		57344: 26, // $end (10x)
		57376: 27, // equality_expression (9x)
		57381: 28, // logical_and_expression (8x)
		57377: 29, // expression (7x)
		57380: 30, // graph_description_list (3x)
		57388: 31, // statement_suffix (3x)
		57356: 32, // DOT (2x)
		57379: 33, // graph_description (2x)
		57386: 34, // statement (2x)
		57375: 35, // argument_expression_list (1x)
		57351: 36, // COLONEQUAL (1x)
		57349: 37, // EQUALS (1x)
		57378: 38, // formula (1x)
		57350: 39, // PARAMEQUAL (1x)
		57387: 40, // statement_list (1x)
		57373: 41, // $default (0x)
		57358: 42, // DOLLAR (0x)
		57345: 43, // error (0x)
		57357: 44, // POUND (0x)
		57372: 45, // UNARY (0x)
	}

	yySymNames = []string{
		"MINUS",
		"COMMA",
		"SEMI",
		"OR",
		"RPAREN",
		"ID",
		"LPAREN",
		"NUM",
		"AND",
		"NOT",
		"STRING",
		"EQ",
		"NE",
		"GE",
		"GT",
		"LE",
		"LT",
		"PLUS",
		"postfix_expression",
		"primary_expression",
		"unary_expression",
		"DIVIDE",
		"multiplicative_expression",
		"TIMES",
		"additive_expression",
		"relational_expression",
		"$end",
		"equality_expression",
		"logical_and_expression",
		"expression",
		"graph_description_list",
		"statement_suffix",
		"DOT",
		"graph_description",
		"statement",
		"argument_expression_list",
		"COLONEQUAL",
		"EQUALS",
		"formula",
		"PARAMEQUAL",
		"statement_list",
		"$default",
		"DOLLAR",
		"error",
		"POUND",
		"UNARY",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {38, 1},
		2:  {40, 1},
		3:  {40, 2},
		4:  {34, 4},
		5:  {34, 4},
		6:  {34, 10},
		7:  {34, 2},
		8:  {31, 1},
		9:  {31, 2},
		10: {30, 2},
		11: {30, 3},
		12: {33, 1},
		13: {19, 1},
		14: {19, 1},
		15: {19, 1},
		16: {19, 3},
		17: {18, 1},
		18: {18, 4},
		19: {18, 3},
		20: {35, 1},
		21: {35, 3},
		22: {20, 1},
		23: {20, 2},
		24: {20, 2},
		25: {22, 1},
		26: {22, 3},
		27: {22, 3},
		28: {24, 1},
		29: {24, 3},
		30: {24, 3},
		31: {25, 1},
		32: {25, 3},
		33: {25, 3},
		34: {25, 3},
		35: {25, 3},
		36: {27, 1},
		37: {27, 3},
		38: {27, 3},
		39: {28, 1},
		40: {28, 3},
		41: {29, 1},
		42: {29, 3},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [81][]uint8{
		// 0
		{55, 5: 47, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 58, 59, 27: 60, 61, 48, 34: 46, 38: 44, 40: 45},
		{26: 43},
		{55, 5: 47, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 58, 59, 42, 60, 61, 48, 34: 123},
		{41, 5: 41, 41, 41, 9: 41, 41, 26: 41},
		{30, 30, 30, 30, 6: 85, 8: 30, 11: 30, 30, 30, 30, 30, 30, 30, 21: 30, 23: 30, 32: 86, 36: 109, 108, 39: 110},
		// 5
		{1: 102, 100, 90, 30: 101, 99},
		{29, 29, 29, 29, 29, 8: 29, 11: 29, 29, 29, 29, 29, 29, 29, 21: 29, 23: 29},
		{28, 28, 28, 28, 28, 8: 28, 11: 28, 28, 28, 28, 28, 28, 28, 21: 28, 23: 28},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 58, 59, 27: 60, 61, 97},
		{26, 26, 26, 26, 26, 8: 26, 11: 26, 26, 26, 26, 26, 26, 26, 21: 26, 23: 26},
		// 10
		{21, 21, 21, 21, 21, 8: 21, 11: 21, 21, 21, 21, 21, 21, 21, 21: 21, 23: 21},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 96},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 95},
		{18, 18, 18, 18, 18, 8: 18, 11: 18, 18, 18, 18, 18, 18, 18, 21: 18, 23: 18},
		{15, 15, 15, 15, 15, 8: 15, 11: 15, 15, 15, 15, 15, 15, 15, 21: 77, 23: 76},
		// 15
		{74, 12, 12, 12, 12, 8: 12, 11: 12, 12, 12, 12, 12, 12, 73},
		{1: 7, 7, 7, 7, 8: 7, 11: 7, 7, 71, 69, 70, 68},
		{1: 4, 4, 4, 4, 8: 4, 11: 65, 66},
		{1: 2, 2, 2, 2, 8: 62},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 58, 59, 27: 64},
		// 20
		{30, 30, 30, 30, 30, 6: 85, 8: 30, 11: 30, 30, 30, 30, 30, 30, 30, 21: 30, 23: 30, 32: 86},
		{1: 3, 3, 3, 3, 8: 3, 11: 65, 66},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 58, 84},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 58, 67},
		{1: 5, 5, 5, 5, 8: 5, 11: 5, 5, 71, 69, 70, 68},
		// 25
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 83},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 82},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 81},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 72},
		{74, 8, 8, 8, 8, 8: 8, 11: 8, 8, 8, 8, 8, 8, 73},
		// 30
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 80},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 75},
		{13, 13, 13, 13, 13, 8: 13, 11: 13, 13, 13, 13, 13, 13, 13, 21: 77, 23: 76},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 79},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 78},
		// 35
		{16, 16, 16, 16, 16, 8: 16, 11: 16, 16, 16, 16, 16, 16, 16, 21: 16, 23: 16},
		{17, 17, 17, 17, 17, 8: 17, 11: 17, 17, 17, 17, 17, 17, 17, 21: 17, 23: 17},
		{14, 14, 14, 14, 14, 8: 14, 11: 14, 14, 14, 14, 14, 14, 14, 21: 77, 23: 76},
		{74, 9, 9, 9, 9, 8: 9, 11: 9, 9, 9, 9, 9, 9, 73},
		{74, 10, 10, 10, 10, 8: 10, 11: 10, 10, 10, 10, 10, 10, 73},
		// 40
		{74, 11, 11, 11, 11, 8: 11, 11: 11, 11, 11, 11, 11, 11, 73},
		{1: 6, 6, 6, 6, 8: 6, 11: 6, 6, 71, 69, 70, 68},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 58, 59, 27: 60, 61, 89, 35: 88},
		{5: 87},
		{24, 24, 24, 24, 24, 8: 24, 11: 24, 24, 24, 24, 24, 24, 24, 21: 24, 23: 24},
		// 45
		{1: 93, 4: 92},
		{1: 23, 3: 90, 23},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 58, 59, 27: 60, 91},
		{1: 1, 1, 1, 1, 8: 62},
		{25, 25, 25, 25, 25, 8: 25, 11: 25, 25, 25, 25, 25, 25, 25, 21: 25, 23: 25},
		// 50
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 58, 59, 27: 60, 61, 94},
		{1: 22, 3: 90, 22},
		{19, 19, 19, 19, 19, 8: 19, 11: 19, 19, 19, 19, 19, 19, 19, 21: 19, 23: 19},
		{20, 20, 20, 20, 20, 8: 20, 11: 20, 20, 20, 20, 20, 20, 20, 21: 20, 23: 20},
		{3: 90, 98},
		// 55
		{27, 27, 27, 27, 27, 8: 27, 11: 27, 27, 27, 27, 27, 27, 27, 21: 27, 23: 27},
		{36, 5: 36, 36, 36, 9: 36, 36, 26: 36},
		{35, 5: 35, 35, 35, 9: 35, 35, 26: 35},
		{1: 106, 105},
		{5: 104, 33: 103},
		// 60
		{1: 33, 33},
		{1: 31, 31},
		{34, 5: 34, 34, 34, 9: 34, 34, 26: 34},
		{5: 104, 33: 107},
		{1: 32, 32},
		// 65
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 58, 59, 27: 60, 61, 121},
		{55, 5: 63, 51, 49, 9: 54, 50, 18: 53, 52, 56, 22: 57, 24: 58, 59, 27: 60, 61, 119},
		{6: 111},
		{7: 112},
		{1: 113},
		// 70
		{7: 114},
		{1: 115},
		{7: 116},
		{4: 117},
		{2: 118},
		// 75
		{37, 5: 37, 37, 37, 9: 37, 37, 26: 37},
		{1: 102, 100, 90, 30: 101, 120},
		{38, 5: 38, 38, 38, 9: 38, 38, 26: 38},
		{1: 102, 100, 90, 30: 101, 122},
		{39, 5: 39, 39, 39, 9: 39, 39, 26: 39},
		// 80
		{40, 5: 40, 40, 40, 9: 40, 40, 26: 40},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("'%c'", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 43

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 4:
		{
			if _, ok := yyS[yypt-1].expr.(*stringexpr); ok {
				lexer, _ := yylex.(*yylexer)
				_context.addError(GeneralError(lexer.lineno, lexer.column, "string can't be right value"))
			}
			yyVAL.expr = AssignmentExpression(_context, yyS[yypt-3].str, yyS[yypt-1].expr, false)
			_context.addOutput(yyVAL.expr.VarName(), yyS[yypt-0].descriptions, 0, 0)
		}
	case 5:
		{
			if _, ok := yyS[yypt-1].expr.(*stringexpr); ok {
				lexer, _ := yylex.(*yylexer)
				_context.addError(GeneralError(lexer.lineno, lexer.column, "string can't be right value"))
			}
			yyVAL.expr = AssignmentExpression(_context, yyS[yypt-3].str, yyS[yypt-1].expr, false)
			_context.addNotOutputVar(yyVAL.expr.VarName(), yyS[yypt-0].descriptions, 0, 0)
		}
	case 6:
		{
			yyVAL.expr = ParamExpression(_context, yyS[yypt-9].str, yyS[yypt-6].value, yyS[yypt-4].value, yyS[yypt-2].value)
		}
	case 7:
		{
			if _, ok := yyS[yypt-1].expr.(*stringexpr); ok {
				lexer, _ := yylex.(*yylexer)
				_context.addError(GeneralError(lexer.lineno, lexer.column, "string can't be right value"))
			}
			varName := _context.newAnonymousVarName()
			yyVAL.expr = AssignmentExpression(_context, varName, yyS[yypt-1].expr, true)
			_context.addOutput(varName, yyS[yypt-0].descriptions, 0, 0)
		}
	case 9:
		{
			yyVAL.descriptions = yyS[yypt-1].descriptions
		}
	case 10:
		{
			if !IsValidDescription(yyS[yypt-0].str) {
				lexer, _ := yylex.(*yylexer)
				_context.addError(BadGraphDescError(lexer.lineno, lexer.column, yyS[yypt-0].str))
			}
			yyVAL.descriptions = append(yyVAL.descriptions, yyS[yypt-0].str)
		}
	case 11:
		{
			if !IsValidDescription(yyS[yypt-0].str) {
				lexer, _ := yylex.(*yylexer)
				_context.addError(BadGraphDescError(lexer.lineno, lexer.column, yyS[yypt-0].str))
			}
			yyVAL.descriptions = append(yyS[yypt-2].descriptions, yyS[yypt-0].str)
		}
	case 12:
		{
			yyVAL.str = yyS[yypt-0].str
		}
	case 13:
		{
			expr := _context.defined(yyS[yypt-0].str)
			if expr == nil {
				expr = _context.definedParam(yyS[yypt-0].str)
			}
			if expr != nil {
			} else if funcName, ok := noArgFuncMap[yyS[yypt-0].str]; ok {
				expr = FunctionExpression(_context, funcName, nil)
			} else {
				lexer, _ := yylex.(*yylexer)
				_context.addError(UndefinedVarError(lexer.lineno, lexer.column, yyS[yypt-0].str))
				expr = ErrorExpression(_context, yyS[yypt-0].str)
			}
			yyVAL.expr = expr
		}
	case 14:
		{
			yyVAL.expr = ConstantExpression(_context, yyS[yypt-0].value)
		}
	case 15:
		{
			yyVAL.expr = StringExpression(_context, yyS[yypt-0].str[1:len(yyS[yypt-0].str)-1])
		}
	case 16:
		{
			yyVAL.expr = yyS[yypt-1].expr
		}
	case 17:
		{
			yyVAL.expr = yyS[yypt-0].expr
		}
	case 18:
		{
			if _, ok := funcMap[yyS[yypt-3].str]; !ok {
				lexer, _ := yylex.(*yylexer)
				_context.addError(UndefinedFunctionError(lexer.lineno, lexer.column, yyS[yypt-3].str))
				yyVAL.expr = ErrorExpression(_context, yyS[yypt-3].str)
			} else {
				yyVAL.expr = FunctionExpression(_context, yyS[yypt-3].str, yyS[yypt-1].arguments)
			}
		}
	case 19:
		{
			if !_context.isReferenceSupport(yyS[yypt-2].str, yyS[yypt-0].str) {
				lexer, _ := yylex.(*yylexer)
				_context.addError(GeneralError(lexer.lineno, lexer.column, __yyfmt__.Sprintf("%s.%s not supported", yyS[yypt-2].str, yyS[yypt-0].str)))
				yyVAL.expr = ErrorExpression(_context, yyS[yypt-0].str)
			} else {
				yyVAL.expr = ReferenceExpression(_context, yyS[yypt-2].str, yyS[yypt-0].str)
			}
		}
	case 20:
		{
			yyVAL.arguments = []expression{yyS[yypt-0].expr}
		}
	case 21:
		{
			yyVAL.arguments = append(yyVAL.arguments, yyS[yypt-0].expr)
		}
	case 22:
		{
			yyVAL.expr = yyS[yypt-0].expr
		}
	case 23:
		{
			yyVAL.expr = UnaryExpression(_context, yyS[yypt-1].str, yyS[yypt-0].expr)
		}
	case 24:
		{
			yyVAL.expr = UnaryExpression(_context, yyS[yypt-1].str, yyS[yypt-0].expr)
		}
	case 25:
		{
			yyVAL.expr = yyS[yypt-0].expr
		}
	case 26:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}
	case 27:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}
	case 28:
		{
			yyVAL.expr = yyS[yypt-0].expr
		}
	case 29:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}
	case 30:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}
	case 31:
		{
			yyVAL.expr = yyS[yypt-0].expr
		}
	case 32:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}
	case 33:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}
	case 34:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}
	case 35:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}
	case 36:
		{
			yyVAL.expr = yyS[yypt-0].expr
		}
	case 37:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}
	case 38:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}
	case 39:
		{
			yyVAL.expr = yyS[yypt-0].expr
		}
	case 40:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}
	case 41:
		{
			yyVAL.expr = yyS[yypt-0].expr
		}
	case 42:
		{
			yyVAL.expr = BinaryExpression(_context, yyS[yypt-1].str, yyS[yypt-2].expr, yyS[yypt-0].expr)
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
