-----------------------------------------------------------
-- GENERATED BY EASYLANG COMPILER.
-- !!!! DON'T MODIFY IT!!!!!!
-----------------------------------------------------------

MACDBUYClass = {}

MACDBUYClass['name'] = 'MACDBUY'
MACDBUYClass['argName'] = {}

MACDBUYClass['vars'] = {'做多'}
MACDBUYClass['flags'] = {0x00000000}
MACDBUYClass['color'] = {{Red=-1, Green=-1, Blue=-1}}
MACDBUYClass['lineThick'] = {1}
MACDBUYClass['lineStyle'] = {0}
MACDBUYClass['graphType'] = {1}

function MACDBUYClass:new(data)
    print('MACDBUYClass:new')
    o = {}
    setmetatable(o, self)
    self.__index = self
    o.__data_code0___ = data

    o.formula_code0__macd = FormulaManager.NewFormula('MACD', o.__data_code0___)
    o.var1 = o.formula_code0__macd.GetVarValue('DIF')
    o.var2 = o.formula_code0__macd.GetVarValue('DEA')
    o.var4 = CROSS(o.var1, o.var2)
    o.var3 = o.var4

    o.drawTextActions = {

    }

    o.drawIconActions = {

    }

    o.drawLineActions = {

    }

    o.drawKLineActions = {

    }

    o.stickLineActions = {

    }

    o.ployLineActions = {

    }

    o.ref_values = {o.var3}
    return o
end

function MACDBUYClass:updateLastValue()
    print("MACDBUYClass:updateLastValue")
    o.formula_code0__macd.UpdateLastValue()
    o.var4.UpdateLastValue()
end

function MACDBUYClass:Len()
    print("MACDBUYClass:Len")
    return self.__data_code0___.Len()
end


function MACDBUYClass:Get(index)
    return {
        o.var3.Get(index),
    }
end

FormulaClass = MACDBUYClass
	